### ISSUE TITLE
Cannot feed value of shape

### ISSUE THREAD

**Issue by AlexYoung757** [HsiaoYetGun/ESIM#6]
thank you for your share .  when  i  run this code. here is an error as follows:
ValueError: Cannot feed value of shape (32, 100) for Tensor 'premise_actual_length:0', which has shape '(?,)'

i know that it's a simple problem,and just the shape is not match. but how to solve it?

**Comment by randomtutu** [comment]
first version of the code  has some bugs and difference with the original code (ESIM) wirte by the  **theano**.
if u want to run the first version code , u could add some lines in the **Train.py**  as line 51

>     premise_mask_train = np.sum(premise_mask_train, axis=1)
>     hypothesis_mask_train = np.sum(hypothesis_mask_train, axis=1)
>     premise_mask_dev = np.sum(premise_mask_dev, axis=1)
>     hypothesis_mask_dev = np.sum(hypothesis_mask_dev, axis=1)

elif u want to run the same progress like the code write by **theano**.  u could change the part of anttention in the  Model.py as https://github.com/pengshuang/Text-Similarity/blob/master/models/ESIM.py in logical

**Comment by AlexYoung757** [comment]
thanks for your reply, i have solved this problem. So it's just a theano version .
